name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # runs daily
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: "header, repositories"
          config_timezone: "America/Phoenix"
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: >-
            Jupyter Notebook
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_habits: yes
          plugin_habits_from: all
          plugin_habits_facts: yes
          plugin_lines: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_traffic: yes
          plugin_followup: yes
