name: GitHub Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install Python deps
      - name: Install deps
        run: pip install requests

      # Generate weather file
      - name: Fetch Arizona weather
        run: python scripts/weather.py

      # Generate metrics (with weather inside)
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          base: "header, repositories"
          config_timezone: "America/Phoenix"

          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_lines: yes
          plugin_traffic: yes
          plugin_followup: yes

          # inject the weather
          plugin_custom: yes
          plugin_custom_source: weather.md
